GET http://localhost:5000/users


###
GET http://localhost:5000/users/1


###
POST http://localhost:5000/users
Content-Type: application/json

{
    "name": "Fikri",
    "email": "jasdfasdfohasdfasdfasdn@gmail.com",
    "gender": "Male"
}


###

PATCH  http://localhost:5000/users/1
Content-Type: application/json

{
    "id":"1",
    "name": "M Fajar",
    "email": "gagasdfahn@gmail.com",
    "gender": "Male"
}


###
DELETE   http://localhost:5000/users/1
Content-Type: application/json

{
    "id":"1"
}